### Get People
GET https://swapi.dev/api/people/

### Get vehicles
GET https://swapi.dev/api/vehicles/

### Get species
GET https://swapi.dev/api/species/

### Get planets
GET https://swapi.dev/api/planets/

### Get Homeworld

GET https://swapi.dev/api/planets/1/
